import "./globals.css";
import type { Metadata } from "next";
import { Inter, Inclusive_Sans } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const inclusiveSans = Inclusive_Sans({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--custom-font-inclusive-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inclusiveSans.variable}>
      <body className={inclusiveSans.className}>{children}</body>
    </html>
  );
}
